name: maerp-postgresql

services:
  maerp.server:
    image: ${DOCKER_REGISTRY-}maerpserver
    build:
      context: .
      dockerfile: src/maERP.Server/Dockerfile
    environment:
      - DatabaseConfig__Provider=PostgreSQL
      - DatabaseConfig__ConnectionString=Host=postgresql;Port=5432;Database=maerp_01;Username=maerp;Password=maerp;
    ports:
      - 8443:443
      - 8080:80
    depends_on:
      postgresql:
        condition: service_healthy
      grafana-agent:
        condition: service_started
    networks:
      - backend

  maerp.browser:
    image: ${DOCKER_REGISTRY-}maerpbrowser
    build:
      context: .
      dockerfile: src/maERP.UI.Browser/Dockerfile
    environment:
      - SERVER_URL=https://maerp.server:443
    ports:
      - 8444:443
      - 8081:80
    depends_on:
      - maerp.server
    networks:
      - backend

  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: maerp_01
      POSTGRES_USER: maerp
      POSTGRES_PASSWORD: maerp
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - maerp-postgresql-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maerp -d maerp_01"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  grafana-agent:
    image: grafana/agent:latest
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: grafana-agent
      REMOTE_WRITE_HOST: mimir:9009
      POSTGRES_HOST: postgresql:5432
    ports:
      - "12345:12345"
    networks:
      - backend

volumes:
  maerp-postgresql-data:

networks:
  backend:
    driver: bridge