name: maerp-mariadb

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8443:443"
      - "8444:444"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - maerp.server
      - maerp.browser
    networks:
      - backend

  maerp.server:
    image: ${DOCKER_REGISTRY-}maerp/server
    build:
      context: .
      dockerfile: src/maERP.Server/Dockerfile
    environment:
      - DatabaseConfig__Provider=MySQL
      - DatabaseConfig__ConnectionString=Server=mariadb;Port=3306;Database=maerp_01;Uid=maerp;Pwd=maerp;
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    depends_on:
      mariadb:
        condition: service_healthy
      grafana-agent:
        condition: service_started
    networks:
      - backend

  maerp.browser:
    image: ${DOCKER_REGISTRY-}maerp/web
    build:
      context: .
      dockerfile: src/maERP.UI.Browser/Dockerfile
    environment:
      - SERVER_URL=http://maerp.server:80
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    depends_on:
      - maerp.server
    networks:
      - backend

  mariadb:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: maerp_01
      MARIADB_USER: maerp
      MARIADB_PASSWORD: maerp
    ports:
      - "3306:3306"
    volumes:
      - maerp-mariadb-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  grafana-agent:
    image: grafana/agent:latest
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: grafana-agent
      REMOTE_WRITE_HOST: mimir:9009
      MARIADB_HOST: mariadb:3306
    ports:
      - "12345:12345"
    networks:
      - backend

volumes:
  maerp-mariadb-data:

networks:
  backend:
    driver: bridge