version: '3.4'

services:
  maerp.web:
    image: ${DOCKER_REGISTRY-}maerpweb
    build:
      context: .
      dockerfile: maERP.Web/Dockerfile
    environment:
      # set server url (example: https://erp-server.domain.tld)
      - SERVER_URL="maerp.server"
    ports:
      - 443:8443
      - 80:8080
    links:
      - maerp.server

  maerp.server:
    image: ${DOCKER_REGISTRY-}maerpserver
    build:
      context: .
      dockerfile: maERP.Server/Dockerfile
    environment:
      - DB_TYPE="mysql"
      - DB_HOST="localhost"
      - DB_PORT="3306"
      - DB_NAME="maerp"
      - DB_USER="maerp"
      - DB_PASS="maerp"
    ports:
      - 443:8080