name: maerp

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - maerp.server
      - maerp.browser
    networks:
      - backend

  maerp.server:
    image: ${DOCKER_REGISTRY-}maerpserver
    build:
      context: .
      dockerfile: src/maERP.Server/Dockerfile
    environment:
      - DatabaseConfig__Provider=Sqlite
      - DatabaseConfig__ConnectionString=Data Source=/app/data/maerp.db
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    volumes:
      - maerp-data:/app/data
    depends_on:
      - grafana-agent
    networks:
      - backend

  maerp.browser:
    image: ${DOCKER_REGISTRY-}maerpbrowser
    build:
      context: .
      dockerfile: src/maERP.UI.Browser/Dockerfile
    environment:
      - SERVER_URL=http://maerp.server:80
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    depends_on:
      - maerp.server
    networks:
      - backend


  grafana-agent:
    image: grafana/agent:latest
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: grafana-agent
      REMOTE_WRITE_HOST: mimir:9009
      POSTGRES_HOST: postgres:5432
    ports:
      - "12345:12345"
    networks:
      - backend

volumes:
  maerp-data:

networks:
  backend:
    driver: bridge