version: '3.4'

services:
  maerp.server:
    image: ${DOCKER_REGISTRY-}maerpserver
    build:
      context: .
      dockerfile: maERP.Server/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=maerp_01;User Id=maerp;Password=maerp
    ports:
      - 8443:443
    depends_on:
      - postgres
      - grafana-agent
    links:
      - postgres
      - grafana-agent
    networks:
      - backend

  maerp.web:
    image: ${DOCKER_REGISTRY-}maerpweb
    build:
      context: .
      dockerfile: maERP.Web/Dockerfile
    environment:
      # set server url (example: https://erp-server.domain.tld)
      - SERVER_URL="maerp.server"
    ports:
      - 8444:443
      - 8080:80
    links:
      - maerp.server

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: maerp
      POSTGRES_PASSWORD: maerp
      POSTGRES_DB: maerp_01
    ports:
      - 5432:5432
    networks:
      - backend

  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/config:/etc/agent-config
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: mimir:9009
      POSTGRES_HOST: postgres:5433
    ports:
      - "12345:12345"
    networks:
      - backend

networks:
  backend:
    driver: bridge