name: maERP.Web Publish

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'src/maERP.Web/**'
      - 'src/maERP.SharedUI/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: maerp/web
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/maERP.Web/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: maerp/web:latest
