name: maERP.Server Build and Test

on:
  push:
    branches-ignore: [ main ]
    paths:
      - '.github/workflows/**'
      - 'src/maERP.Server/**'
      - 'src/maERP.Core/**'
      - 'src/maERP.Domain/**'
      - 'src/maERP.Application/**'
      - 'src/maERP.Analytics/**'
      - 'src/maERP.Identity/**'
      - 'src/maERP.Infrastructure/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.Persistence.MySQL/**'
      - 'src/maERP.Persistence.MSSQL/**'
      - 'src/maERP.Persistence.PosgreSQL/**'
      - 'src/maERP.SalesChannels/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.Application.Persistence.IntegrationTests/**'
      - 'src/maERP.Application.UnitTests/**'
      - 'src/maERP.Server.Tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/maERP.Server/**'
      - 'src/maERP.Core/**'
      - 'src/maERP.Domain/**'
      - 'src/maERP.Application/**'
      - 'src/maERP.Analytics/**'
      - 'src/maERP.Identity/**'
      - 'src/maERP.Infrastructure/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.SalesChannels/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.Persistence.MySQL/**'
      - 'src/maERP.Persistence.MSSQL/**'
      - 'src/maERP.Persistence.PostgreSQL/**'
      - 'src/maERP.Application.Persistence.IntegrationTests/**'
      - 'src/maERP.Application.UnitTests/**'
      - 'src/maERP.Server.Tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore maERP.Server.Tests
        run: dotnet restore tests/maERP.Server.Tests
      - name: Build maERP.Server.Tests
        run: dotnet build tests/maERP.Server.Tests
      - name: Test maERP.Server.Tests
        run: dotnet test tests/maERP.Server.Tests --no-build --verbosity normal