name: maERP.Server Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'maERP.Server/**'
      - 'maERP.Core/**'
      - 'maERP.Domain/**'
      - 'maERP.Application/**'
      - 'maERP.Ai/**'
      - 'maERP.Analytics/**'
      - 'maERP.Identity/**'
      - 'maERP.Infrastructure/**'
      - 'maERP.Persistence/**'
      - 'maERP.SalesChannels/**'
      - 'maERP.Persistence/**'
      - 'maERP.Application.Persistence.IntegrationTests/**'
      - 'maERP.Application.UnitTests/**'
      - 'maERP.Server.Tests/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore maERP.Server.Tests
        run: dotnet restore maERP.Server.Tests
      - name: Build maERP.Server.Tests
        run: dotnet build maERP.Server.Tests --no-restore
      - name: Test maERP.Server.Tests
        run: dotnet test maERP.Server.Tests --no-build --verbosity normal
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: maerp/server
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./maERP.Server/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: maerp/server:latest